version: '3.7'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  etcd:
    image: bitnami/etcd
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - '2379:2379'

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    # volumes:
    #   - ./data:/data
    ports:
      - 2182:2181
    environment:
    # 匿名登录--必须开启
    - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.60:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      # KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    # volumes:
    #   - ./kafka-logs:/kafka
    depends_on:
      - zookeeper